### ISSUE TITLE
Env file not taken into account when building services

### ISSUE THREAD

**Issue by claustres** [kalisio/kargo#111]
As build scripts rely on `docker build` and not docker compose the env file is not read. If the service build depends on some env var (e.g. kano) it will not be correct.

**Comment by cnouguier** [comment]
When building, the .env is read:
https://github.com/kalisio/kargo/blob/master/kargo#L139

In the Change end point screen, the URL of the platform is correct but it is read from the API:
https://github.com/kalisio/kCore/blob/master/src/client/components/authentication/KChangeEndpoint.vue#L80

Should we use the information from the API or from the client. The client need to be rebuilt to be overriden.

**Comment by claustres** [comment]
My explanation was not clear, the problem is not in the kargo command but rather in the Docker build command used in the build script where the env is not passed. The sole available mean seems to be using build-time variables for this purpose (https://vsupalov.com/docker-build-pass-environment-variables/): see https://github.com/kalisio/kargo/commit/d32a49519ae5a7d743fbcc65a885d2ecdf9e7367.

The API URL is actually read from the client config as well https://github.com/kalisio/kCore/blob/master/src/client/api.js#L137. This URL is just an example but there are others values depending on env var in the client config build like NODE_ENV, NODE_APP_INSTANCE, etc. So if they are not correctly passed to the build we will have discrepancies between the frontend and the backend config.
