### ISSUE TITLE
Allow to specify additional Grafana dashboards

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kargo#210]

**Comment by robinbourianes-kalisio** [comment]
Is it not enough to have additional grafana dashboard in the kargo workspace  ?
Like we do [here](https://github.com/kalisio/kargo-workspaces/tree/odk-prod/configs/grafana/provisioning/dashboards) for mongodb metrics ?

**Comment by cnouguier** [comment]
No longer relevant since we moved to K8S
