### ISSUE TITLE
Add a maximum number of attempts when restarting a service

### ISSUE THREAD

**Issue by claustres** [kalisio/kargo#231]
The base restart policy is `on-failure` with default options meaning never give up to restart a service. This typically leads to tons of alerts when eg a database service fails because after that all connected apps/jobs will also fail recurrently on restart.

Maybe it is a good idea to set a [maximum number of attempts](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy) before giving up to restart a service. It could also help to limit alerts by playing with the `delay` and `window` options.

**Comment by cnouguier** [comment]
Is it still relevant since we moved to K8S ?
