### ISSUE TITLE
Default traefik TLS configuration exhibits weak ciphers in SSL tests

### ISSUE THREAD

**Issue by claustres** [kalisio/kargo#257]
It appears the CBC ciphers are now weak according to SSL Labs, we should only provide secure suites by default, see [this issue](https://stackoverflow.com/questions/52128979/recommended-tls-ciphers-for-traefik) as reference. 

More information about the impact of insecure suites [here](https://success.qualys.com/discussions/s/question/0D52L00004TnykTSAR/security-impact-of-weak-cipher-suites).

**Comment by claustres** [comment]
We could probably use what is recommended by [Mozilla](https://ssl-config.mozilla.org/#server=traefik&server-version=1.7.12&config=intermediate) by default.

**Comment by cnouguier** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=kapp.dev.kalisio.xyz looks fine
