### ISSUE TITLE
deploy error at startup: ./kargo: line 302: COM/KISLYUK/YQ_CONSTRAINTS: invalid variable name

### ISSUE THREAD

**Issue by coutouly** [kalisio/kargo#302]
hello,
i read the tuto from: https://kalisio.github.io/kargo/guides/getting-started.html#install-the-prerequisites
i use the .env.sample

./kargo deploy services
initializing service redis
./kargo: line 302: COM/KISLYUK/YQ_CONSTRAINTS: invalid variable name

any help would be appriciate
thanks
lucile

**Comment by claustres** [comment]
Hi, we need more context to help: information about your infrastructure, output logs, etc.

Did you correctly setup your workspace (https://kalisio.github.io/kargo/guides/getting-started.html#setup-your-workspace) ?

**Comment by cnouguier** [comment]
No longer relevant since we moved to K8S
